services:
  bitcoind:
    image: ruimarinho/bitcoin-core:26.0
    command: ["-regtest", "-printtoconsole", "-rpcallowip=0.0.0.0/0", "-rpcbind=0.0.0.0", "-rpcuser=bitcoin", "-rpcpassword=bitcoin"]
    ports:
      - "18443:18443"
    volumes:
      - bitcoin-data:/home/bitcoin/.bitcoin

volumes:
  bitcoin-data:
